routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', array('uses' => 'HomeController@index'));



Route::group(['prefix' => 'virtual-tour'], function(){
    Route::get('/', array('uses' => 'HomeController@showVirtualTour'))->name('virtual.tour');
    Route::get('/{handle}',array('uses' => 'Client\VirtualTourController@viewVirtualTour'))->name('view.tour');
});

Route::group(['prefix' => 'post'], function(){
    Route::get('/{handle}',array('uses' => 'Client\PostController@viewPost'))->name('view.post');
});

Route::auth();

Route::group(['prefix' => 'admin','middleware' => 'admin'], function(){
    Route::get('/dashboard', 'Admin\AdminController@showAnnouncements')->name('admin.dashboard');
    Route::get('/announcements','Admin\AdminController@showAnnouncements')->name('admin.announcements');
    Route::get('/posts','Admin\AdminController@showPosts')->name('admin.posts');
    Route::get('/videos','Admin\AdminController@showVideos')->name('admin.videos');
    Route::get('/users','Admin\AdminController@showUsers')->name('admin.users');
    Route::get('/site-settings','Admin\AdminController@showSiteSettings')->name('admin.site-settings');
    Route::get('/virtual-tours','Admin\AdminController@showVirtualSettings')->name('admin.virtual-tours');

    Route::group(['namespace' => 'Admin','middleware' => 'admin'], function(){
        Route::resource('user','UserResource');
        Route::get('user/{user}/delete', [
            'as' => 'user.destroy',
            'uses' => 'UserResource@destroy'
        ]);

        Route::resource('announcement','AnnouncementResource');
        Route::get('announcement/{user}/delete', [
            'as' => 'announcement.destroy',
            'uses' => 'AnnouncementResource@destroy'
        ]);

        Route::resource('post','PostResource');

        Route::resource('video','VideoResource');

        Route::resource('site-setting','SiteSettingsResource');

        Route::resource('virtual-tour','VirtualTourResource');
    });
});

Route::resource('contact','ContactController');
Route::resource('promo','PromoController');

resources/views/admin/add_announcement.blade.php
@extends('layouts.admin')
@section('title', 'Add Announcement')
@section('content')
    <h3><i class="fa fa-bullhorn"></i> Announcements</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="form-panel">
                <h4 class="mb"><span class="fa fa-user"></span> Add Announcement</h4>
                <ul>
                    @foreach($errors->all() as $error)
                        <li class="alert alert-danger">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
                {{Form::open(['url' => route('announcement.store'), 'class' => 'form-horizontal style-form', 'method' => 'post','files' => true])}}
                <div class="form-group">
                    <label class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-9">
                        {{Form::text('text',Input::old('name'),['name' => 'name', 'id' => 'name', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-9">
                        {{Form::textarea('text',Input::old('description'),['name' => 'description', 'id' => 'description', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 control-label">End Date</div>
                    <div class="col-sm-3">
                        {{Form::date('text', Input::old('end_date'),['name' => 'end_date', 'id' => 'end_date', 'class' => 'form-control'])}}
                    </div>
                    <div class="col-sm-1 control-label">Featured</div>
                    <div class="col-sm-3">
                        <input type="checkbox" name="is_featured" value="0" data-toggle="switch" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 control-label">Set Featured Image</div>
                    <div class="col-md-10">
                        {{Form::file('featured',array('class' => 'file','id' => 'imgInp'))}}
                    </div>
                    <div class="col-md-5 top-buffer">
                        <img id="img-upload" style='width:100%;'>
                    </div>
                </div>
                <div class="form-group">
                </div>
                <button type="submit" class="btn btn-success"> Add Announcement</button>
                {{form::close()}}
            </div>
        </div>
    </div>
@stop

resources/views/admin/add_post.blade.php
@extends('layouts.admin')
@section('title', 'Add Post')
@section('content')
    <h3><i class="fa fa-tags"></i> Posts</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="form-panel">
                <h4 class="mb"><span class="fa fa-user"></span> Add Post</h4>
                <ul>
                    @foreach($errors->all() as $error)
                        <li class="alert alert-danger">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
                {{Form::open(['url' => route('post.store'), 'class' => 'form-horizontal style-form', 'method' => 'post','files' => true])}}
                <div class="form-group">
                    <label class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-9">
                        {{Form::text('text',Input::old('title'),['name' => 'title', 'id' => 'name', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-9">
                        {{Form::textarea('text',Input::old('description'),['name' => 'description', 'id' => 'description', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 control-label">Set Featured Image</div>
                    <div class="col-md-10">
                        {{Form::file('featured',array('class' => 'file','id' => 'imgInp'))}}
                    </div>
                    <div class="col-md-5 top-buffer">
                        <img id="img-upload" style='width:100%;'>
                    </div>
                </div>
                <div class="form-group">
                </div>
                <button type="submit" class="btn btn-success"> Add Post</button>
                {{form::close()}}
            </div>
        </div>
    </div>
@stop

resources/views/admin/add_user.blade.php
@extends('layouts.admin')
@section('title', 'Add User')
@section('content')
    <h3><i class="fa fa-users"></i> Users</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="form-panel">
                <h4 class="mb"><span class="fa fa-user"></span> Add User</h4>
                <ul>
                    @foreach($errors->all() as $error)
                        <li class="alert alert-danger">
                        {{ $error }}
                        </li>
                    @endforeach
                </ul>
                {{Form::open(['url' => route('user.store'), 'class' => 'form-horizontal style-form', 'method' => 'post'])}}
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label class="col-sm-1 col-sm-1 control-label">First Name</label>
                        <div class="col-sm-3">
                            {{Form::text('text',Input::old('firstname'),['name' => 'firstname', 'id' => 'firstname', 'class' => 'form-control'])}}
                        </div>
                        <label class="col-sm-1 col-sm-1 control-label">Last Name</label>
                        <div class="col-sm-3">
                            {{Form::text('text',Input::old('lastname'),['name' => 'lastname', 'id' => 'lastname', 'class' => 'form-control'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-1 col-sm-1 control-label">Email</div>
                        <div class="col-sm-7">
                            {{Form::email('email',Input::old('email'),['name' => 'email', 'id' => 'email', 'class' => 'form-control'])}}

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-1 col-sm-1 control-label">Password</div>
                        <div class="col-sm-3">
                            {{Form::password('password',['name' => 'password', 'id' => 'password', 'class' => 'form-control'])}}
                        </div>
                        <div class="col-sm-1 col-sm-1 control-label">Confirm Password</div>
                        <div class="col-sm-3">
                            {{Form::password('password_confirmation',['name' => 'password_confirmation', 'id' => 'password_confirmation', 'class' => 'form-control'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-1 col-sm-1 control-label">Role</div>
                        <div class="col-md-3">
                            <select multiple name="role" class="form-control">
                                @foreach($roles as $role)
                                    <option value="{{$role->handle}}">{{$role->name}}</option>
                                @endforeach
                            </select>
                            <span class="help-block">Press control to select multiple roles.</span>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Add User</button>
                {{form::close()}}
            </div>
        </div>
    </div>
@stop

resources/views/admin/add_video.blade.php
@extends('layouts.admin')
@section('title', 'Add Video')
@section('content')
    <h3><i class="fa fa-tags"></i> Videos</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="form-panel">
                <h4 class="mb"><span class="fa fa-user"></span> Add Video</h4>
                <ul>
                    @foreach($errors->all() as $error)
                        <li class="alert alert-danger">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
                {{Form::open(['url' => route('video.store'), 'class' => 'form-horizontal style-form', 'method' => 'post','files' => true])}}
                <div class="form-group">
                    <label class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-9">
                        {{Form::text('text',Input::old('title'),['name' => 'title', 'id' => 'name', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-9">
                        {{Form::textarea('text',Input::old('description'),['name' => 'description', 'id' => 'description', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 control-label">Add Video</div>
                    <div class="col-md-10">
                        {{Form::file('featured',array('class' => 'file','id' => 'imgInp'))}}
                    </div>
                    <div class="col-md-5 top-buffer">
                        <img id="img-upload" style='width:100%;'>
                    </div>
                </div>
                <div class="form-group">
                </div>
                <button type="submit" class="btn btn-success"> Add Video</button>
                {{form::close()}}
            </div>
        </div>
    </div>
@stop

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')
@section('title', 'Dashboard')
@section('content')
    <!--main content start-->
    <section id="main-content">

    </section>
    <!--main content end-->
@stop

resources/views/admin/edit_announcement.blade.php
@extends('layouts.admin')
@section('title', 'Edit Announcement')
@section('content')
    <h3><i class="fa fa-bullhorn"></i> Announcements</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="form-panel">
                <h4 class="mb"><span class="fa fa-user"></span> {{$announcement->id ? 'Edit' : 'Add'}} Announcement</h4>
                <ul>
                    @foreach($errors->all() as $error)
                        <li class="alert alert-danger">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
                {{Form::open(['url' => $announcement->id ? route('announcement.update',$announcement->id) : route('announcement.store'), 'class' => 'form-horizontal style-form', 'method' => $announcement->id ? 'put' : 'post','files' => true])}}
                <div class="form-group">
                    <label class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-9">
                        {{Form::text('text',$announcement->name ? $announcement->name : Input::old('name'),['name' => 'name', 'id' => 'name', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-9">
                        {{Form::textarea('text',$announcement->description ? $announcement->description : Input::old('description'),['name' => 'description', 'id' => 'description', 'class' => 'form-control','maxlength' => '255'])}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 control-label">End Date</div>
                    <div class="col-sm-3">
                        {{Form::date('text',$announcement->end_date ? date('Y-m-d',strtotime($announcement->end_date)) : Input::old('end_date'),['name' => 'end_date', 'id' => 'end_date', 'class' => 'form-control'])}}
                    </div>
                    <div class="col-sm-1 control-label">Featured</div>
                    <div class="col-sm-3">
                        {!! Form::checkbox('is_featured',1,$announcement->is_featured === 1,array('data-toggle' => 'switch')) !!}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 control-label">Set Featured Image</div>
                    <div class="col-md-10">
                        {{Form::file('featured',array('class' => 'file','id' => 'imgInp'))}}
                    </div>
                    <div class="col-md-5 top-buffer">
                        <img id="img-upload" src="{{asset($announcement->featured_image)}}" style='width:100%;' alt="{{$announcement->name}}">
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Update Announcement</button>
                {{form::close()}}
            </div>
        </div>
    </div>
@stop

resources/views/admin/edit_video.blade.php
@extends('layouts.admin')
@section('title', 'Edit Video')
@section('content')
    <h3><i class="fa fa-tags"></i> Videos</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="form-panel">
                <h4 class="mb"><span class="fa fa-user"></span> Edit Video</h4>
                <ul>
                    @foreach($errors->all() as $error)
                        <li class="alert alert-danger">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
                {{Form::open(['url' => $video->id ? route('video.update',$video->id) : route('video.store'), 'class' => 'form-horizontal style-form', 'method' => $video->id ? 'put' : 'post','files' => true])}}
                <div class="form-group">
                    <label class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-9">
                        {{Form::text('text',$video->title ? $video->title : Input::old('title'),['name' => 'title', 'id' => 'title', 'class' => 'form-control'])}}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-9">
                        {{Form::textarea('text',$video->description ? $video->description : Input::old('description'),['name' => 'description', 'id' => 'description', 'class' => 'form-control','maxlength' => '255'])}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 control-label">Set Featured Image</div>
                    <div class="col-md-10">
                        {{Form::file('featured',array('class' => 'file','id' => 'imgInp'))}}
                    </div>
                    <div class="col-md-5 top-buffer">
                        <img id="img-upload" src="{{asset($video->featured_image)}}" style='width:100%;' alt="{{$video->name}}">
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Update Video</button>
                {{form::close()}}
            </div>
        </div>
    </div>
@stop

resources/views/admin/posts.blade.php
@extends('layouts.admin')
@section('title', 'Posts')
@section('content')
    <h3><i class="fa fa-tags"></i> Posts</h3>
    <div class="row mt">
        <div class="col-md-12">
            <div class="form-panel">
                <section id="no-more-tables">
                    <h4><i class="fa fa-table"></i> Post Lists <a href="{{route('post.index')}}" class="btn btn-success pull-right"><span class="fa fa-plus"></span> Add New Post</a></h4>
                    <hr>
                    @if(count($posts) > 0)
                        <table class="table table-striped table-condensed cf">
                            <thead class="cf">
                            <tr>
                                <th></th>
                                <th><i class="fa fa-bullhorn"></i> Title</th>
                                <th><i class="fa fa-question-circle"></i> Description</th>
                                <th><i class="fa fa-user"></i> Author</th>
                                <th><i class=" fa fa-calendar"></i> Date Created</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td class="centered">
                                        <a href="{{route('post.edit',$post->id)}}">
                                            <img src="{{$post->featured_image ? asset($post->featured_image) : asset('images/default/default.gif')}}" alt="{{$post->title}}" class="img-circle" height="42" width="42">
                                        </a>
                                    </td>
                                    <td data-title="Title"><a href="{{route('post.edit',$post->id)}}">{{$post->title}}</a></td>
                                    <td data-title="Description">{!! str_limit($post->description,100,'...') !!}</td>
                                    <td data-title="Author">{{str_limit($post->user->name)}}</td>
                                    <td data-title="Date Created">{{date('M d, Y, D',strtotime($post->created_at))}}</td>
                                    <td>
                                        <a href="{{route('post.edit',$post->id)}}" class="btn btn-primary btn-xs"><i class="fa fa-pencil "></i></a>
                                        @if(count($posts) > 1)
                                            <a href="{{route('post.destroy',$post->id)}}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <p>No Results Found</p>
                    @endif
                </section>
            </div>
        </div>
    </div>
@stop

resources/views/admin/site_settings.blade.php
@extends('layouts.admin')
@section('title', 'Site Settings')
@section('content')
    <h3><i class="fa fa-gear"></i> Settings</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="form-panel">
                <h4 class="mb"><span class="fa fa-gears"></span> Site Settings</h4>
                <ul>
                    @foreach($errors->all() as $error)
                        <li class="alert alert-danger">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
                {{Form::open(['url' => route('site-setting.store'), 'class' => 'form-horizontal style-form', 'method' => 'post'])}}
                @foreach($siteSettings as $setting)
                    <div class="form-group">
                        <label class="col-md-2 col-sm-12 control-label">{{$setting['settings_name']}}</label>
                        <div class="col-sm-10">
                            {{Form::text('text',$setting['settings_value'],['name' => $setting['settings_key'], 'id' => $setting['settings_key'], 'class' => 'form-control','required' => 'required'])}}
                        </div>
                    </div>
                @endforeach

                <button type="submit" class="btn btn-success">Update Settings</button>
                {{Form::close()}}
            </div>
        </div>
    </div>
@stop

resources/views/admin/users.blade.php
@extends('layouts.admin')
@section('title', 'Users')
@section('content')
    <h3><i class="fa fa-users"></i> Users</h3>
    <div class="row mt">
        <div class="col-md-12">
            <div class="form-panel">
                <section id="no-more-tables">
                    <h4><i class="fa fa-table"></i> User Lists <a href="{{route('user.index')}}" class="btn btn-success pull-right"><span class="fa fa-plus"></span> Add new user</a></h4>
                    <hr>
                    @if(count($users) > 0)
                    <table class="table table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th><i class="fa fa-user"></i> Name</th>
                                <th><i class="fa fa-envelope"></i> Email</th>
                                <th><i class="fa fa-tasks"></i> Role</th>
                                <th><i class=" fa fa-calendar"></i> Created</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td data-title="Name"><a href="{{route('user.edit',$user->id)}}">{{$user->name}}</a></td>
                                <td data-title="Email">{{$user->email}}</td>
                                <td data-title="Role">
                                    @foreach($user->roles as $role)
                                        {{$role->name}}
                                    @endforeach
                                </td>
                                <td data-title="Created">{{date('M d, Y h:m:s a, D',strtotime($user->created_at))}}</td>
                                <td data-title="">
                                    <a href="{{route('user.edit',$user->id)}}" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></a>
                                    @if(count($users) > 1)
                                        <a href="{{route('user.destroy',$user->id)}}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @else
                        <p>No Results Found</p>
                    @endif
                </section>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="pull-right">
                            {{ $users->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/videos.blade.php
@extends('layouts.admin')
@section('title', 'Videos')
@section('content')
    <h3><i class="fa fa-tags"></i> Videos</h3>
    <div class="row mt">
        <div class="col-md-12">
            <div class="form-panel">
                <section id="no-more-tables">
                    <h4><i class="fa fa-table"></i> Video Lists <a href="{{route('post.index')}}" class="btn btn-success pull-right"><span class="fa fa-plus"></span> Add New Video</a></h4>
                    <hr>
                    @if(count($videos) > 0)
                        <table class="table table-striped table-condensed cf">
                            <thead class="cf">
                            <tr>
                                <th><i class="fa fa-bullhorn"></i> Title</th>
                                <th><i class="fa fa-question-circle"></i> Description</th>
                                <th><i class="fa fa-user"></i> Author</th>
                                <th><i class=" fa fa-calendar"></i> Date Created</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($videos as $video)
                                <tr>
                                    <td data-title="Title"><a href="{{route('video.edit',$video->id)}}">{{$video->title}}</a></td>
                                    <td data-title="Description">{!! str_limit($video->description,100,'...') !!}</td>
                                    <td data-title="Author">{{str_limit($video->user->name)}}</td>
                                    <td data-title="Date Created">{{date('M d, Y, D',strtotime($video->created_at))}}</td>
                                    <td>
                                        <a href="{{route('video.edit',$video->id)}}" class="btn btn-primary btn-xs"><i class="fa fa-pencil "></i></a>
                                        @if(count($videos) > 1)
                                            <a href="{{route('video.destroy',$video->id)}}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <p>No Results Found</p>
                    @endif
                </section>
            </div>
        </div>
    </div>
@stop

resources/views/admin/virtual_tours.blade.php
@extends('layouts.admin')
@section('title', 'Posts')
@section('content')
    <h3><i class="fa fa-map-marker"></i> Virtual Tours</h3>
    <div class="row mt">
        <div class="col-md-12">
            <div class="form-panel">
                <section id="no-more-tables">
                    <h4><i class="fa fa-table"></i> Virtual Tour Lists <a href="{{route('virtual-tour.index')}}" class="btn btn-success pull-right"><span class="fa fa-plus"></span> Add New Virtual Tour</a></h4>
                    <hr>
                    @if(count($virtual_tours) > 0)
                        <table class="table table-striped table-condensed cf">
                            <thead class="cf">
                            <tr>
                                <th></th>
                                <th><i class="fa fa-location-arrow"></i> Location</th>
                                <th><i class="fa fa-map-marker"></i> Coordinates</th>
                                <th><i class=" fa fa-calendar"></i> Date Created</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($virtual_tours as $virtual_tour)
                                <tr>
                                    <td class="centered">
                                        <a href="{{route('post.edit',$virtual_tour->id)}}">
                                            <img src="{{$virtual_tour->featured_image ? asset($virtual_tour->featured_image) : asset('images/default/default.gif')}}" alt="{{$virtual_tour->name}}" class="img-circle" height="42" width="42">
                                        </a>
                                    </td>
                                    <td data-title="Location"><a href="{{route('virtual-tour.edit',$virtual_tour->id)}}">{{$virtual_tour->name}}</a></td>
                                    <td data-title="Coordinates">Longitude : {{$virtual_tour->longitude}} <br> Latitude : {{$virtual_tour->latitude}}</td>
                                    <td data-title="Date Created">{{date('M d, Y, D',strtotime($virtual_tour->created_at))}}</td>
                                    <td>
                                        <a href="{{route('virtual-tour.edit',$virtual_tour->id)}}" class="btn btn-primary btn-xs"><i class="fa fa-pencil "></i></a>
                                        @if(count($virtual_tours) > 1)
                                            <a href="{{route('virtual-tour.destroy',$virtual_tour->id)}}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <p>No Results Found</p>
                    @endif
                </section>
            </div>
        </div>
    </div>
@stop